<?php

namespace ContainerLeVJD5I;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5w2K4PQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5w2K4PQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5w2K4PQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user_repository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'user_repository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
