<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLeVJD5I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLeVJD5I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLeVJD5I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLeVJD5I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLeVJD5I\App_KernelDevDebugContainer([
    'container.build_hash' => 'LeVJD5I',
    'container.build_id' => '2fb306fd',
    'container.build_time' => 1676128960,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLeVJD5I');
